#!/bin/bash

ACTION=${1:-start}

case $ACTION in

  start)
    echo "cleaning logs"
    rm -f logs/*.log

    echo "starting RP"
    forever start RP/server.js

    sleep 2

    echo "starting DN0"
    forever start DN/dn0s1/server.js
    forever start DN/dn0s2/server.js
    forever start DN/dn0s3/server.js
    ;;

  stop)
    echo "stopping DN0"
    forever stop DN/dn0s3/server.js
    forever stop DN/dn0s2/server.js
    forever stop DN/dn0s1/server.js

    echo "stopping RP"
    forever stop RP/server.js
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  stat)
    forever list
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|stat}"
    exit 1
    ;;

esac
